import type { Metadata } from "next";
import "./globals.css";
import { getLocale } from "next-intl/server";
import { ClientProviders } from "./providers";
import { NextIntlClientProvider } from "next-intl";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body
        theme-mode="dark"
      >
        {/* NextIntlClientProvider must use in server component */}
        <NextIntlClientProvider>
          <ClientProviders >
            {children}
          </ClientProviders>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}
